name: Check Content Links

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  Check:
    name: Check Content Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun linkCheck.ts
